name: Apply Stack Instances

on: 
  workflow_dispatch:
    inputs:
      wait-time:
        description: 'Time to wait between plan and apply: 30s, 5m, 1h'
        required: true
        default: '1m'

jobs:
  terraform:
    runs-on: ubuntu-20.04
    steps:

      - name: Install Terraform
        run: |
          cd ~
          sudo apt update
          sudo apt install -y unzip wget
          sudo wget "https://releases.hashicorp.com/terraform/$(curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r -M '.current_version')/terraform_$(curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r -M '.current_version')_linux_amd64.zip"
          sudo unzip terraform*.zip
          sudo chmod +x terraform
          terraform --version

      - name: Checkout Respository
        uses: actions/checkout@v2
        with:
          ref: main
          path: ./repository-files/

      - name: Terraform Init
        env:
          TF_VAR_TENANCY_OCID:     "${{ secrets.TF_VAR_TENANCY_OCID }}"
          TF_VAR_COMPARTMENT_OCID: "${{ secrets.TF_VAR_COMPARTMENT_OCID }}" 
          TF_VAR_USER_OCID:        "${{ secrets.TF_VAR_USER_OCID }}"
          TF_VAR_FINGERPRINT:      "${{ secrets.TF_VAR_FINGERPRINT }}"
          TF_VAR_PRIVATE_KEY:      "${{ secrets.TF_VAR_PRIVATE_KEY }}"
          TF_VAR_PUBLIC_KEY:       "${{ secrets.TF_VAR_PUBLIC_KEY }}"
          TF_VAR_REGION:           "${{ secrets.TF_VAR_REGION }}"
        run:  cd ./repository-files/ && ls -la && ~/terraform init

      - name: Terraform Plan
        env:
          TF_VAR_TENANCY_OCID:     "${{ secrets.TF_VAR_TENANCY_OCID }}"
          TF_VAR_COMPARTMENT_OCID: "${{ secrets.TF_VAR_COMPARTMENT_OCID }}" 
          TF_VAR_USER_OCID:        "${{ secrets.TF_VAR_USER_OCID }}"
          TF_VAR_FINGERPRINT:      "${{ secrets.TF_VAR_FINGERPRINT }}"
          TF_VAR_PRIVATE_KEY:      "${{ secrets.TF_VAR_PRIVATE_KEY }}"
          TF_VAR_PUBLIC_KEY:       "${{ secrets.TF_VAR_PUBLIC_KEY }}"
          TF_VAR_REGION:           "${{ secrets.TF_VAR_REGION }}"
        run:  cd  ./repository-files/ && ~/terraform plan 

      - name: Wait Before Apply
        run:  sleep  "${{ github.event.inputs.wait-time }}" || sleep "1m"

      - name: Terraform Apply
        env:
          TF_VAR_TENANCY_OCID:     "${{ secrets.TF_VAR_TENANCY_OCID }}"
          TF_VAR_COMPARTMENT_OCID: "${{ secrets.TF_VAR_COMPARTMENT_OCID }}" 
          TF_VAR_USER_OCID:        "${{ secrets.TF_VAR_USER_OCID }}"
          TF_VAR_FINGERPRINT:      "${{ secrets.TF_VAR_FINGERPRINT }}"
          TF_VAR_PRIVATE_KEY:      "${{ secrets.TF_VAR_PRIVATE_KEY }}"
          TF_VAR_PUBLIC_KEY:       "${{ secrets.TF_VAR_PUBLIC_KEY }}"
          TF_VAR_REGION:           "${{ secrets.TF_VAR_REGION }}"
        run:  cd ./repository-files/ && ~/terraform apply -auto-approve